---
title: "Tom Horlacher"
author: "DK"
date: "2024-05-26"
draft: yes
categories: [neighbors]
---

It was my turn to transport persons from SLC Airport to home.

They were coming home after an extended visit to Korea.

By the time, we drove home, I had missed my sacrament meeting.

Noticed that families were heading to the chapel.

Made the meeting of the Pleasant View 8th Ward.

There was an empty seat, Brother Tom Horlacher was seating nearby.

The speaker spoke of growing up in Panaca, Nevada.

Rays of Light in our lives.

His experience of tithing. Parents re-arranged their lives to be full tithe payers.

"Not enough room to receive it"

Escobedos Ariel and Shule

The town I passed on the way home via Alamo, NV.

The whole area, Caliente, Panaca, and Pioche are parts of Lincoln County.

After the meeting continue to visit.

Learned that Josef and Christina Kujanpaa have 6 children and are teaching them 3 languages.

-   Finnish

-   Mandarin

-   English

They will visit Finland for 1.5 months. They feel their children are speaking more English than they prefer.

------------------------------------------------------------------------

Tom and I touched on various topics.

Learn that he studied German literature.

He served mission in Germany and his wife, Helga is from Berlin.

His father and his father's cousin fought on both sides of the war.

Decline of religion in Europe.

Work ethics of Germans

Are we worried about the youth?

No there will be miracles to sustain them.
