---
title: "Keeps You Running"
author: "DK"
date: "2024-05-28"
draft: yes
categories: [oldies]
---

Like a text message from an old friend, a memorable song or a long forgotten artist can pop into one's mind.

Michael McDonald replaced Tom Johnston of the Doobie Brothers, as their lead singer.

It is difficult to think of a group as same, when fitted with a new lead singer

But not only replace but McDonald also produced his unique sound.

More soulful than before

As a high schooler listening to their Greatest Album, they were so distant.

Not humanly relatable.

Now he has a memoir highlighting weakness and deadly affects of drugs and alcohol.

He had to decide or be dead within a decade.

In an article highlighting a turning point in his career, his life.

> "I've learned that my greatest strengths going off into the future is remembering my past and remembering it vividly and not getting amnesia, not thinking that I've got this because I never will have this,"

<https://people.com/michael-mcdonald-sober-27-years-after-being-thrown-out-of-wifes-recovery-meeting-drunk-exclusive-8650197>

Furthermore,

> "It's really a one day at a time thing for me, and I have to make that decision every day in a renewed effort to just live this day out in the best way I can," McDonald concludes. "The beauty of that is that all of a sudden you turn around one day and it seems like a blink of an eye and you're looking at 30 years behind you of one day at a time, and that's life too."

------------------------------------------------------------------------

<https://www.npr.org/2024/05/20/1252416210/michael-mcdonald-what-a-fool-believes>

> "More than anything, I think what people who suffer from addiction share universally is that we're kind of hiding from ourselves. We're kind of hiding from our feelings," he says. "I've learned in sobriety to slowly peel back different layers."

------------------------------------------------------------------------

<https://guideposts.org/positive-living/health-and-wellness/coping-with-illness/how-faith-helped-michael-mcdonald-let-go-of/>

You know, I still have that old dream sometimes. It happens when I try too hard to shape the future instead of taking things one day at a time. We have to let go in life. Allow a Higher Power to take the wheel and trust we’ll be taken care of no matter what. That’s how I try to live, minute by minute.

------------------------------------------------------------------------

> He continues, “And after I got over that, I suddenly realized this is that moment that I have to make a decision. The bus is leaving one more time, and I might not be here when it comes back. And I had so much to lose in that moment.”

<https://healingproperties.org/michael-mcdonald-comes-clean-with-what-a-fool-believes/>
