---
title: "EQ Party"
author: "DK"
date: "2024-06-13"
draft: yes
categories: [neighborhood]
---

Attended EQ Social

Dick Thomas opened his home.

NIce backyard pool and tennis/pickel ball courts.

Tables were set up nicely.

A few dozen brothers showed up.

I see a person I hadn't seen for a while

It's Peter Hubbard, the one who sold the home to us 22 years ago.

His son Parker also came, he has 3 sisters.

David Wright, Clair Ralph, Greg Hadley, Paul Dunn and Ed Hunt.

Ed Hunt knows a lot about the neighborhood and he would not let go of the microphone.

Our home was once occupied by the Boyds, then Bartons.

Boyds worked as a secret service agent.

Clair Ralphs graduating class of 1953 had a few dozen students.

Down to less than 10 people.

Downey, Idaho.

Brother Wright had 350 people graduating in 1964.

135 have passed away.

Ed Hunt sold his 1956 Chevy he bough back in 1969 for \$100

He sold it for over \$10,000

Rode his Schwinn Sting Ray, I used to have one, a Yellow One.

Then played Pickel Ball, for the first time, with Wayne Ross.

Then a dip in the pool.

Good 2 hours spent.

Went to walk around the track at Provo Rec.

17,509 steps today

---

Met Embassy Mike that works in India Embassy.

Struggles of India.
