---
title: "Country Living"
author: "DK"
date: "2024-05-31"
draft: yes
categories: [neighbors]
---

> Is poverty with security is better than plenty in the midst of fear and uncertainty

One day, the city mouse went to the countryside to visit the country mouse. Seeing the country mouse's meager food, the city mouse felt sorry for him and invited the country mouse to the city, promising that there were plenty of delicious foods to eat there. The city mouse took the country mouse to a kitchen full of food and told him to eat as much as he wanted. Although the country mouse was envious of the city mouse and tried to eat the food, he couldn't because people kept coming in, forcing him to run away each time. Unable to eat, he only ended up hungrier. The country mouse then said to the city mouse, "No matter how much delicious food there is here, it's better to live in the countryside, where I can live peacefully, even if the food is humble." With that, he returned to the countryside. Depending on the version, the setting can appear as a field and a granary instead of the city and countryside.

This is a story that most Koreans know, originally an Aesop's Fable.

어느날 서울쥐가 시골쥐를 만나려고 시골에 갔다. 서울쥐는 시골쥐의 초라한 음식을 보고 가엾게 여겨, 시골쥐에게 서울에는 맛있는 음식이 얼마든지 있으니 실컷 먹여 주겠다면서 시골쥐를 서울로 초대했다. 서울쥐가 시골쥐를 음식이 풍부한 부엌으로 데리고 가서 그곳에 쌓여 있는 음식을 맘껏 먹으라고 했다. 시골쥐가 서울쥐를 부러워하면서 음식을 먹으려고 했는데, 그때마다 사람이 들어오는 바람에 번번이 도망하느라고 음식을 먹지 못하고 배만 곯았다. 시골쥐는 서울쥐에게 “맛있는 음식이 아무리 많다 해도 마음 편히 먹을 수 없는 여기보다는 초라하더라도 속 편하게 살 수 있는 시골이 더 낫다.”고 말하고는 시골로 돌아가 버렸다. 각편에 따라서 배경 공간이 서울과 시골 대신 들판과 집에 있는 광으로 나타나기도 한다.

<https://encykorea.aks.ac.kr/Article/E0028066#:~:text=%E3%80%8C%EC%84%9C%EC%9A%B8%EC%A5%90%20%EC%8B%9C%EA%B3%A8%EC%A5%90%E3%80%8D%EB%8A%94,%EC%A4%91%20%EB%8F%99%EB%AC%BC%EC%9A%B0%ED%99%94%EC%97%90%20%EC%86%8D%ED%95%9C%EB%8B%A4.>

<https://www.read.gov/aesop/004.html>

Now days one doesn't have to choose.

City living will come to you whether you asked for it or not.

Is it possible to take just the part you want and leave the rest.

Exposed to taste, sound and convenience of the city life can go back to the country life?

A la carte

City living is available to all, even if one is living in the country.

Via internet.

---

Made inevitable comparison.

California weather and prosperity with Utah austerity.

Felt like in Asia.

---
