---
title: "황해도 Lady"
author: "DK"
date: "2024-06-07"
draft: yes
categories: [logic]
---

> You fell victim to one of the classic blunders!
>
> The most famous of which is, 'never get involved in a land war in Asia,' but only slightly less well-known is this: 'Never go in against a Sicilian when death is on the line!'"

-   Vizzini from the movie `Princess Bride`

I would add,

> Never get into an argument with a Christian, bourgeoisie lady from 황해도 (黃海道).

Especially, if her name happens to be, 황현실.

Maybe because of her upbringing in a Christian home or because, she became a head of a household with passing of her father at age 14.

She had to take care of 5 younger siblings and her mother.

There was no chance you would win the argument.

The only unknown was whether the defeat would be a technical knockout or go few rounds.

It all depended on how Mom was feeling that moment.

I don't know how she developed her reasoning and logic but they were not only convincing but often fierce in delivery.

------------------------------------------------------------------------

She taught a mixture of stories from the Bible and old Korea.

She brought heaven a bit closer to home.

At the same time, lifted us above the worldly things.

Thought of 한석봉 story.

My mom tested me.

I am sure I disappointed her.

She brought heaven close to us at the same time lifting us closer.

She did it by admonishing us.
