---
title: "Meeting with Elders Hui and Park"
author: "DK"
date: "2024-08-17"
draft: yes
categories: [LA]
---

Planned for our 35th Wedding Anniversary.

Chosen destination was Los Angeles basin, more specifically the area known as Orange County.

Provo Airport offers destinations to major Western cities, including Orange County/Santa Ana Airport (SNA) now commonly know as John Wayne Airport.

Combined the air travel with a travel package offered by Costco.

Once decided, contacted Elder Hui Ho Shun who was in the Mandarin language program in the Los Angeles district.

Also, through 김상현, obtained and talked to 박성철 (Kevin).

Dates were set.

Meet Hui for lunch.

Visit Park for dinner on Saturday.

------------------------------------------------------------------------

Hui chose Capital Seafood for the meeting.

We arrived in SNA little after 8AM, after leaving home at 5:30AM.

Less sleep than normal, due to the excitement of visiting the old mission area.

Hui was Stake President of Hacienda Heights, CA, called in August 2023\^\[<https://newsroom.churchofjesuschrist.org/article/new-stakes-and-stake-presidencies-announced-in-september-2023#:~:text=HACIENDA%20HEIGHTS%20CALIFORNIA%20STAKE:%20(Aug.%206%2C%202023),York%20Life%20financial%20professional;%20succeeding%20Craig%20A.>}

After serving as a counselor.

**HACIENDA HEIGHTS CALIFORNIA STAKE:** (Aug. 6, 2023) President — **Ho Shun Hui**, 60, New York Life financial professional; succeeding Craig A. Rigby; wife, Mee Lin Nora Lee Hui. Counselors — **Brian Marti Francis**, 51, AT&T senior advanced analytics employee; wife, Martha Elizabeth Taylor Francis. **John Steven Peterson**, 65, chiropractor; wife, Kathleen Carol Berry Westbrook-Peterson.

Spoke of working with young people.

Teach them principles and let them be in charge.

He had become an enlightened one.

------------------------------------------------------------------------

Kevin Park is an orthopedic surgeon living in Buena Park, CA.

His wife is a dentist.

Her father is a Swiss German, who worked for Nestle and travelled the world.

Her mother is from Taiwan, who was a teacher.

They met when he served in Taiwan as a Catholic missionary

During their global service, they met their god mother, a YTL of Malaysia.
