---
title: "Kongming (孔明)"
author: "DK"
date: "2024-05-22"
draft: yes
categories: [consumer]
---

Vital to a life in high desert is moisture.
Specifically, the amount of snow or rain received and stored during the Water Year. 
Water year goes from 1 Oct to 30 Sept.
However the vast majority of moisture is received during the months of October through April

There is no shortage of places that track and record the most up to date data.

There are those brave enought to predict.
Much like leading indicators or futures in the stock market.

I prefer to follow the lagging indicator.

Stream flow at Rock Canyon.

On a good year, the stream starts in April and flows until July
However, it depends on snowpack and temperatures during April

The legendary exploits of Zhuge Liang tells of his ability to control the weather.
It was more of knowing local conditions and pattern of observations.
Gave him an edge when the storms,in particular winds may prevail.

Trying to be more of Kong Ming.

But satisfied with terrestrial observation of celestial sent events.




In Utah, we get approximately 95% of our water from snowpack. Reservoir storage is dependent upon snowpack and runoff to get us through dry years.
https://water.utah.gov/snowpack/


## References

https://en.wikipedia.org/wiki/Zhuge_Liang?oldformat=true

https://www.nrcs.usda.gov/wps/portal/wcc/home/quicklinks/states/utah/snow/current/