---
title: "Land Flowing with Milk"
author: "DK"
date: "2024-05-19"
draft: yes
categories: [church]
---

Growing up in Korea after the war meant nearly all things were scarce.

There were somethings one could wish for but never attain or not enough.

Two of those were milk and green bananas.

The bananas were in short supply and they were always green and expensive.

I didn't realize the natural color of bananas were yellow until I came to America.

Nor did I get to find out the taste of it while in Korea.

We had a bottle of milk delivered to our home, when I began school.

The milk came in a 12 ounce bottle and 3 of us found creative ways to divide the content.

The contested and divided milk was savored.

Wished for a time when milk and bananas can be had in abundance.

------------------------------------------------------------------------

There is a noodle shop in West Valley where many Koreans congregate.

I see people my age and older.

However, I also see the next generation and their friends as well.

The daughter of the owner commented that I know nearly everyone that visit the store.

I meet at least one person I know when I visit.

It is because I belong to that group of Koreans that still remember times when food was scarce and that eating out meant a financial burden, often a celebration.

It was a set offering. Eating out meant Korean-Chinese restaurant

They serve several dishes but most people order one of 2 dishes.

짜장면[^1] and 짬뽕[^2]

[^1]: <https://namu.wiki/w/%EC%A7%9C%EC%9E%A5%EB%A9%B4>

[^2]: https://namu.wiki/w/%EC%A7%AC%EB%BD%95

These noodles were reserved for special occasions, during growing up years.

And in those rare moments of splurging, we would order 탕수육[^3]

[^3]: https://namu.wiki/w/%ED%83%95%EC%88%98%EC%9C%A1

First bite reminds or triggers memories of difficult days growing up and helps me realize how far we have improved.

Now days these dishes are consumed not for its taste but for nostalgia and sentimental reasons.

------------------------------------------------------------------------

Nowadays, I live in a place that is flowing with milk and honey[^4].

[^4]: https://www.biblegateway.com/passage/?search=Exodus%203%3A17&version=KJV

As well as any other food that mankind has deemed desirable.

Now that basic needs are met. Did I set my goals too low.

Need to recognize the blessings.

In some ways, my standard of living surpasses, kings and queens of Chosun Dynasty.

---\
\
