---
title: "Nothing New Under Sun"
author: "DK"
date: "2024-08-21"
draft: true
categories: [LA]
---

According to Ecclesiastes[^1],

[^1]: https://biblehub.com/kjv/ecclesiastes/1.htm

> The thing that hath been, it *is that* which shall be; and that which is done *is* that which shall be done: and *there is* no new *thing* under the sun.

Then there should be no nightly `News` But there are news, updated minute by minute.

This seems to contradict Heraclitus,

> No man ever steps in the same river twice, for it's not the same river and he's not the same man.

------------------------------------------------------------------------

Prior to certain age, the life seems forever changing. Learn to read patterns in life and read other people.

Then life becomes equal for everyone, See Appendix, @sec-equalization

When the comparison stops. Uniqueness can blossom.

Endless cycle but the man is different.

20s version 30s version

Last year, last month.

------------------------------------------------------------------------

## 인생의 평준화 {#sec-equalization}

40대에는 욕망의 평준화가 일어납니다. 누구나 사회적 성공을 위해 발버둥치며 달려갑니다 처자식 먹여 살리기 위해, 다가오는 노년을 준비하기위해 가장 왕성하게 뛰는 이 나이는 욕망과 책임의 평준화 연령입니다.

50대에는 지식의 평준화가 일아닙니다. 명문대를 졸업한 사람이나 초등학교밖에 다니지 못한 사람이나 아는 게 다 그게 그거 입니다. 살면서 얻는 지식이란 것이 다 그렇고 그런 것 입니다.

60대는 외모의 평준화가 일어납니다. 미스코리아 출신이나 식당 아줌마나 그 얼굴이 그 얼굴입니다. 나이 들면 화장하고 분 발라도 윤기가 흐르지 않는 건 마찬가지입니다.

70대에는 성의 평준화가 일어납니다. 남편이 있으나 없으나, 아내가 있으나 없으나 성 관계는 그리 중요한 문제가 아닙니다.

80대에는 부의 평준화입니다. 있는 자나 없는 자나 먹고 사는게 별차이 없습니다. 하루 세끼면 족합니다.

90대에는 생사의 평준화입니다. 죽은 자와 산 자의 경계가 모호해 집니다. 살았다고 죽은 자보다 별로 나은 게 없으며 살아 있어도 죽은 것만 못합니다.

100세 이상이면 드디어 자연속의 평준화가 이루어집니다. 모두 죽으면 한 줌의 흙으로 변하며,누구나 자연 그대로의 모습입니다.

출처 : 본헤럴드(http://www.bonhd.net)

In your 40s, desires begin to level out. Everyone runs and struggles for social success. This age, when people run most vigorously to feed their wife and children and prepare for the approaching old age, is the age of leveling out desires and responsibilities.

Standardization of knowledge does not happen in your 50s. Those who graduated from prestigious universities or those who only attended elementary school know that. All knowledge gained in life is like that.

In your 60s, your appearance begins to level out. Whether it's a Miss Korea contestant or a restaurant lady, that face is the same. As you get older, even if you apply makeup and powder, your skin loses its shine.

Gender equalization occurs in the 70s. Whether you have a husband or not, or whether you have a wife or not, sexual relations are not that important.

In your 80s, wealth levels out. There is no difference in what people eat and how they live. Three meals a day is enough.

In your 90s, life and death become equal. The boundary between the dead and the living becomes blurred. Even if you are alive, you are not much better than the dead, and even if you are alive, you are not as good as dead.

When you are over 100 years old, normalization in nature is finally achieved. When everyone dies, they turn into a handful of dirt, and everyone remains in their natural state.

Source: Bon Herald (http://www.bonhd.net)
