---
title: "Dull and Difficult"
author: "DK"
date: "2024-06-02"
draft: yes
categories: [labels]
---

## Importance of no labels

I am that I am

14 And God said unto Moses, I Am That I Am: and he said, Thus shalt thou say unto the children of Israel, I Am hath sent me unto you.  Exodus 3:14

Something that can be named belongs in that sphere created.

---

Dao De Jing begins

Things that can be named is not the Way.

The tao that can be told
is not the eternal Tao
The name that can be named
is not the eternal Name.

The unnamable is the eternally real.
Naming is the origin
of all particular things.

Stephen Mitchell translation

Labels are at times necessary in this life.but at times it draws too much unnecessary attention.

A challenge for medical device companies and its product is to more good than harm.

Once introduced a new label and coined a term that describe the challenge of inserting a metal cannula and a plastic catheter into a vein.it was named,

`Dull and Difficult` (better suited as a movie title or to describe somone)

It became a lightning rod for pent up complaints.

Some were ready to place blame on something, now they had a target.

Both the label change and the description of the issue, compounded their complaints.For a while, we needed a daily meeting to handle all of the complaints.

------------------------------------------------------------------------

Life as an immigrant has its set of challenges. Starting at a position others have started and passed, generations ago.

In addition, persistent reminder that you are different than locals.

Sometimes verbal sometimes non-verbal, they both served as reminder that I am different.

Most of the time I brushed it off and it didn't help for someone trying to fit in

Good thing I was busy learning. Helped to have a loving, supportive family. Re-enforced by a community of gospel-living saints. Made it through the education system.

One include de-segregation via busing During the Junior High days, while living in Greenbelt, a 20 minute ride to Palmer Park near Landover.

This was cut short by passing a test and getting into a STEM program at Eleanor Roosevelt HS.

------------------------------------------------------------------------

Fast forward 5 years removed from the graduation. I am living near Western and Olympic.

The skyline of downtown LA is visible - on some clear days.

People around me are mostly Koreans. 
First and 2nd generation immigrants.

Next major block, Pico Blvd, Hispanics, I-10 is a hard dividing line.

We seldom ventured south of Olympic,Our area consisted of Vermont to the East Crenshaw to the West Beverly on the North Pico to the South

Our daily neighborhood visits (tracking) was centered in and around the business-centric Wishire Blvd.

It was a great experience to see other Koreans that had immigrated to US.

Seeing how they adjusted, how some have chosen different paths then the original ones then they began on their journey.

Understood the role of Korean churches, more than a religious role, a social network, providing necessities to immigrants. A sense of belonging and proving temporal welfare, shelter, food, job assistance.I didn't feel as lonely.

------------------------------------------------------------------------

Fast forward another 15 years. I am back to where we start our journey. As a family I am in Korea 25 years after leaving

I am married, have children, and have a role and mission to be completed in 4 years.

I am an ex-pat in the country of birth.

I look like others, I talk mostly like others, sans the local Southeastern Korea accent.

However, Koreans are able to pick out the small differences and let me know ways I can improve.

-   We don't use those expressions anymore, that is old Korean
-   How come you don't drink with us after work

Looking back they were just commenting on the difference, in a straight forward, Korean way of welcoming someone.

I have learned to accept it and move on

Having a family with me and the local congregation 수성와드 helped.

------------------------------------------------------------------------

This year marks 50 years that our family have lived in the United States of America.

Have seen many changes about Korea, from the US based persons

When I arrived no one knew where Korea was except those that were associated with the Korean War.

Now nearly everyone know something about the Korean Wave.

Although I can state that I have not changed, I believe I have.

I am still trying to understand and adapt. 
Adept and grow in this environment

Labels and packaging are important My company learned a hard lesson.

I learned a soft lesson

Stick to your basics and instinct to survive But also rely on your heritage, don't let go.

Build on basics and refine and improve

---

iPhones evolve with each iteration.
Older Koreans say 

'10년이면 강산도 변한다'라는 말은 우리에게 친숙한 옛말로, '시간의 흐름 속에서 모든 것은 달라진다'는 의미를 지닙니다.

Although, fondness for old things remain.
Howeveer, move forward.

