---
title: "Utah September" 
author: "DK"
date: "2024-09-22"
draft: yes
categories: [longing]
---

Living in Utah during September is to view a revival of battle of seasons.
Summer is not ready to give up its reign.
Winter give a preview of its prowess.
Autumn battles to get its few weeks

A juxtaposition of 
what has been, 
what is to come
and fleeting nature

---

When young, one regret the passing of summer and start of school.

When older, wonder if there are enough in cash reserves to meet the obligation for the balance of the year.
This one has no control over.

That there will not be a major change at work or the economy that one has no control over.

---

Each season brings reality and pain of unrealizable dreams

The Last leaf summary

"The Last Leaf" by **O. Henry** is a short story set in Greenwich Village, New York, and revolves around themes of hope, sacrifice, and friendship. The story features two struggling artists, **Johnsy** and **Sue**, who share a small apartment. Johnsy falls gravely ill with pneumonia and becomes convinced that she will die when the last leaf falls from the ivy vine outside her window.

As Johnsy's condition worsens, her friend Sue becomes desperate. Their elderly neighbor, **Behrman**, a failed artist who has yet to paint his masterpiece, learns about Johnsy's belief in the falling leaves. That night, during a storm, the last leaf appears to cling to the vine.

The next morning, Johnsy is amazed to see that the last leaf has not fallen. This renewed hope gives her the strength to fight off her illness. Later, it is revealed that Behrman had painted the leaf on the wall to give Johnsy hope, and in doing so, he caught pneumonia himself. Behrman dies as a result of his selfless act, but Johnsy recovers, unaware of his sacrifice.

The story emphasizes the power of art, hope, and human connection. Behrman's act of painting the leaf becomes his masterpiece, representing the idea that sometimes the most significant creations are those that inspire and uplift others.

언제나 돌아오는 계절은 나에게 꿈을 주지만
이룰 수 없는 꿈은 슬퍼요 나를 울려요

---

What dreams to pursue
What dreams to give up
What dreams to modify

September 2024