---
title: "Professional Amateur"
author: "DK"
date: "2024-05-22"
draft: yes
categories: [consumer]
---

Recall speaking to a person at a Art Gallery in Park City.\
\
I was looking at a photo of a Horse Shoe Bend at sunset with threatening clouds.\
I commented the photo didn't represent the location.\
\
The person hearing me said the photo accurately depicted the location.\
I thought to myself, perhaps once a year \
\
As we parted ways,

What constitutes a photo of a location.\
Do we need to create a separate category, fiction and non-fiction photo.\
\
I can understand the need to enhance the photo with available tools.\
However, if we start pulling in elements not present at the time the photo was taken, is that accurate?\

---

How about food?

Often used but entirely inaccurate use of a word - authentic.\
At what point does the sauce over take the food.\

Korean restaurants are hard to commercialize since each area in Korea has its own spin on dishes.

In fact, each family within those area may have a special recipe for Kimchi.

Regional differences may include spice amount variation due to weather factors.

Cooler in north, less salt and spice.

---

Marketing will continue to sell things

\
In life, when is it we are crossing the line,\
A little enhancement or lot of enhancement
