---
title: "As They Appear"
author: "DK"
date: "2024-08-31"
draft: true
categories: [perspective]
---

Am surprised when I visit a place for the second time.

It seems the place has shrank or perhaps I grew bigger.

In any case, the place no longer seem extra ordinary, foreign or large.

Perhaps I should follow the well know quote,

“**一度も登らぬ馬鹿、二度登る馬鹿**”

>“He who climbs Mt. Fuji is a wise man; he who climbs twice is a fool.”

---

I have been a fool, since I like to visit places multiple times.
For me more repetitions, the better

The Church-based wedding celebrations has changed to a venue-based receptions.
Imperceptible yet surely this generation has spoken.

A generation or two ago, weddings were formal and predictable.
Tuxedos for men and formal wedding dresses for women.

Public wedding receptions were held in a large halls in local churches.
With few exceptions beign country clubs.

Now it is reversed, very few church receptions
and mostly held at public venues.

---

Likewise photographers and videographers have evolved.

Friends with access to cameras became the official photographers.
Videographer was the person assigned to run the family-owned video camera.

There were no competition for better angles for photos since very few people brought their own equipment.

The quality of lo-fi and the editing and enhancement was nearly non-existent.
What was shot was what was kept
Raw, or as it happened, literally and figuratively.

Sunrise and Sunset,

It is a continuation of the same.
They are connected.

Husband and wife start out different but inevitably become one.
It is the answer to the mythical question.
Why do we feel separate, alone.

---

The measurement of our efforts cannot be measured instantly

---

The older people like dinners for all of the reasons, plus it is a prelude to a good nights rest.
If our day extend much beyond dinner time, it is an exception.

It allows us to welcome the sunrise.

It is a good day when one can see and greet both the sunrise and the sunset.


---

Work in Progress

A representation of celestial life.
Spotless.

Or rather work in progress

---

In this life
Event coordinator
Taste coordinator

What about next life?

Life coordinators
Wish coordinators