---
title: "CA Weekend Impressions"
author: "DK"
date: "2024-08-20"
draft: true
categories: [LA]
---

Made a rare visit to California.

Last visit was in 2018.

Invitation to home is more meaningful.

Someone that knew me 40 years ago.

A chance to meet and connect with a family.

A momentary home, to be used by another individual.

To provide shelter and moments of respite, rest and renewal.

Home is to provide physical shelter, emotional respite and spriritual renewal

A vacation can do this, money and time is the enabler.

Our earthly home is designed for this.

How about our heavenly home.

We see and hear glimpses more acutely of that home when we travel away from our comfortable surroundings.

But most often the reminder comes through individuals that surround us.

Starting with family and friends.

At times individuals that we encounter.

The cleaning lady at the Hyatt Regency that cleaned our room had the radiance that matched any individual I have met.

She had purpose, her life had meaning. Take off the layers of the world. Tainted by the philosophies of the world.

Butterflies that flew by let us know we are alive.

------------------------------------------------------------------------

Made it to a concert presented by the local Korean Christian Reformed Church. [OKCRC](https://okcrc.org)

A large cross adorned the building. Two large speakers held aloft by the set of cables. A band consisting of drums and guitar

Music is combining factor, higher than religion?

Meeting Iris Kim was a surprise
