---
title: "Highlight Nation"
author: "DK"
date: "2024-06-16"
draft: yes
categories: [lessons]
---

We need someone to bring us down to earth.

My parents did that.

Reminding our place in the world.

Lifting us to be better.

But also bringing the heaven bit closer to us.

2 Stories that highlight shortcoming of Koreans.

Patience and short cut.

빨리빨리 Culture

Short cut mentality.

---

첫 번째 **이야기**는 천제(天帝)의 아들 환웅이 인간세계에 강림하여 나라를 세운 사건을 다룬다. 두 번째 **이야기**는 곰에서 인간으로 화한 웅녀가 환웅과 결혼하여 아들을 낳은 사건을 다룬다. 세 번째 **이야기**는 환웅과 웅녀 사이에 서 태어난 **단군**이 조선을 건국한다는 내용이다.

<https://www.aks.ac.kr/cefia/webzine/2206/focus.html#:~:text=%EC%B2%AB%20%EB%B2%88%EC%A7%B8%20%EC%9D%B4%EC%95%BC%EA%B8%B0%EB%8A%94%20%EC%B2%9C%EC%A0%9C,%EC%9D%84%20%EA%B1%B4%EA%B5%AD%ED%95%9C%EB%8B%A4%EB%8A%94%20%EB%82%B4%EC%9A%A9%EC%9D%B4%EB%8B%A4.>

Had he not succeeded, this story may never been told.

Succeed he did, so we now have this story.

Famous calligrapher

If he didn't become famous, this story wouldn't be told.

## full story\^\[<https://www.wikiwand.com/ko/%ED%95%9C%ED%98%B8>\]

어려서부터 스스로 붓글씨를 익혔으며, 타고난 천재에다 피나는 수련을 쌓았으므로 해·행·진·초(楷行眞草)의 각체가 모두 묘경에 이르렀다. 그는 돈이 없어서 서당을 다니기는커녕 먹과 종이도 살 수가 없었다. 그래서 항아리나 돌 위에 손에 물을 찍어서 글씨 연습을 하였으며, 매일같이 꾸준히 연습하자 글씨를 쓰는 솜씨가 차츰 나아지면서 마을 사람들에게 칭찬을 받았다. 이에 그 어머니는 한호를 유명한 절로 들여보내 공부를 하게 하였는데, 한호의 스승인 승려는 한호를 가르치면서 날이 갈수록 실력이 늘어가는 그의 글 솜씨에 감탄해 마지 않았다.

절에 들어가 공부를 한 지 4년 후, 어느 날 한호는 어머니가 너무나도 보고 싶어서 밤에 몰래 절에서 빠져나와 집으로 찾아왔다. 돌아와서 이미 공부를 많이 해 더는 배울 것이 없다고 하자 어머니는 한호를 불을 끈 어두운 방 안으로 들어오게 한 뒤 자신은 칼로 떡을 썰고 한호는 글씨를 붓으로 쓰게 하여 둘의 솜씨를 비교해 보자고 하였다. 불을 켜고 보니 어머니가 썬 떡은 크기나 두께가 모두 똑같아 보기가 좋았는데, 한호가 쓴 글씨는 서로 크기가 제각각이고 모양이 비뚤비뚤하여 보기가 흉했다. 이에 어머니는 한호를 크게 꾸짖으며 자신의 떡처럼 눈을 감고도 글씨를 고르게 쓸 수 있게 되기 전까지는 집에 올 생각을 하지 말라고 엄명을 하여 한호를 다시 돌려보내 공부하게 하였다는 이야기가 널리 전해 내려져 오고 있다.

## excerpt

한석봉의 어머니는

떡장수를 해서

석봉에게 글씨 공부를

10년간 시킵니다.

​

출가하여 공부하던 석봉은

3년 만에 모친이 보고 싶어서

집으로 돌아왔습니다.

​

모친은 호롱불을 끄고

자신은 떡을 썰고

석봉은 글씨를 쓰게 했습니다.

​

불을 켜 보니 모친의 떡은

보기 좋게 썰어져 있었으나

석봉의 글씨는 엉망입니다.

​

모친은 석봉을 야단쳐서

다시 산으로 보냅니다.

​

결국 석봉은 남은 7년을 채워

문자 그대로 10년 공부를 해서

조선의 명필이 되었습니다.
