---
title: "Olympic Ward Memories 2"
author: "DK"
date: "2024-08-03"
draft: yes
categories: [LA]
---

Used to think that the reason it is the best 18 or 24 months was because,

> ...ye may learn that when ye are in the service of your fellow beings ye are only in the service of your God.

Recently, I have reassessed my time among Korean people in LA. It was indeed the best years of my life -- different reasons than the one King Benjamin gave.

How much time did I spend in the service of others. Did I meet their needs or was I preaching what I wanted them to hear.

Or was it best because I was sheltered from day to day lives that are common.

I didn't have access to mass media material. I totally missed out but I was happier.

Most of all, I was happy since I didn't have the responsibility of being an adult. I was taken care of. Someone was assigned to watch over me, making sure that I did the right thing.

Although it was best of times it was temporary and artificial.

It was my garden of Eden period.

Am I glad

I was happy because I was not exposed to negativity and negative news.

------------------------------------------------------------------------

A responsible life is the one I am comfortable with.

More freedom than I have ever had.

More choices as well.

Would I choose the same path, if given the chance to go back.

Emphatic YES!
