---
title: "17 Months in LA"
author: "DK"
date: "2024-08-16"
draft: yes
categories: [LA]
---

Left home on 18 January 1983

I was endowed on 7 January 1983 in Washington DC Temple.

Left for LA on 16 February. 1983

Left winter in Utah and LA seemed like a paradise

President Harold^[<https://ancestors.familysearch.org/en/KWCC-FS1/harold-whitney-hoopes-1916-1985>] and Virginia^[<https://www.deseret.com/2007/5/24/19757655/obituary-virginia-lee-divers-hoopes-poulson/>] Hoopes greeted me.

My trainer, Matthew Hunt met me and drove me through Beverly Hills.

I had high hopes but when we arrived at 3250 Country Club Drive, I was disappointed.
This area had its heyday, a long time ago.

---

My second mission president was Clarence Campbell^[<https://www.legacy.com/us/obituaries/saltlaketribune/name/clarence-campbell-obituary?id=28462548>] (Elna Shakespeare)

I stayed in the Olympic Ward my entire mission
I also served in the Cerritos Korean Branch
(17909 Bloomfield Ave, Cerritos, CA 90703)

I have stayed in these apartments.

- 3250 Country Club Drive
- 4826 Melrose Avenue
- 16812 Ardmore Avenue
- 9520 Cedar Street
- 200 Mariposa Avenue

---

Although we were missionaries, we got to participate in many ward activities.

- 6 Flags or Magic Mountain
- Olympics
- 돌잔치
- 결혼식
- Hollywood Bowl, Easter Sunrise Service

---

Memorable Food

- Tommy Burger on Beverly (2575 Beverly Blvd, Los Angeles, CA 90057)
- Chinese Restaurant on Olympic
- Chinese Restaurant on Vermont
- Chinese Restaurant on 8th Street
- Chinese Restaurant on 1136 Western
- El Cholo on Western

---

Memorable investigators

- 3 Children of 영빈관 owner
- Relatives of 주현미
- Artist 최
- Kang Family in Beverly Hills, a Temple Square referral
- 화교 friend of 최션녀

---

Memorable Members

- 이태문 1977.12.18 한인 지부 승격. 초대 지부장 이태문 형제 ^[http://www.ldskorea.net/olympic-ward-la-sogae002.htm]
- 박현옥 (Leslie) the hairdresser
- 장 가족 4 girls and a son, 장미리
- 김상복, 상욱, 상민

---

My companions were

- Elder Matthew Hunt (Feb 1983 - Sep 1983)
- Elders Gordon Haws and Daniel See (Sep 1983 - Jan 1984)
- Elder Kevin Park (Jan 1984 - Apr 1984)
- Elder Bak (Apr 1984 - Jul 1984)

I walked LA Koreatown streets and knocked on every Korean apartments at least twice.

I taught and baptized 25 individuals.

Only member that I still keep in touch is 
최귀봉

Taught and baptized the relatives of 주현미
Brother and Sister Yeh

Completed my mission and returned home on 1 August 1984

After serving for 18 months.

I didn't have the option to serve 2 years
